config/routes.rb
Sc2mc::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  # resources :contacts, only: [:new, :create]
  # resources :visitors, only: [:new, :create]

 authenticated :user do
  root to: "home#index", as: :authenticated_root
end

unauthenticated do
  root to: "home#welcome"
end

post 'upload' => 'home#upload', as: 'post_upload'
get 'upload' => 'home#upload', as: 'upload'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

require 'soundcloud'

def index
			
	if current_user
		if current_user.provider == 'soundcloud'
		  @soundcloud_access_token = current_user.access_token 

			 if @soundcloud_access_token != nil

				client = Soundcloud.new({
					  :client_id     => '0a5a8824df0c97aedb12448786a6f1de',
					  :client_secret => 'd57204e408d1cc467f403174788a2397',
					  :access_token      => @soundcloud_access_token
					})

				@sc = client.get('/me')
				@tracks = client.get('/me/tracks')
			end
		end
		@mixcloud_access_token = current_user.mixcloud_access_token 
	end
	
end


def welcome

end

def upload

	@mixcloud_access_token = current_user.mixcloud_access_token 
	@title = params[:track]['title']
	@download_url = params[:track]['download_url']
	@download_url = "#{@download_url}?client_id=0a5a8824df0c97aedb12448786a6f1de" 
	@mp4 = URI.parse(@download_url)


	require 'open-uri'
	require 'open_uri_redirections'
	require 'audioinfo'
	require 'mp4info'

	require 'open-uri'

	open("track", "wb") do |file|
	  open(@download_url, :allow_redirections => :all) do |uri|
	     @file = file.write(uri.read)
	  end
	end


	# open('track.m4a', 'wb') do |file|
	#   file << open(@download_url, :allow_redirections => :all )  {|f| f.read }
	#   @file = file

	#   @mp4 = MP4Info.open(file)

	#   # AudioInfo.open(@file) do |info|
	# 	 #  info.artist   # or info["artist"]
	# 	 #  info.title    # or info["title"]
	# 	 #  info.length   # playing time of the file
	# 	 #  info.bitrate  # average bitrate
	# 	 #  @info = info.to_h     # { "artist" => "artist", "title" => "title", etc... }
	#   # end


	# end
 	
	# require 'json'
	# require 'open-uri'
	# @result = open(@download_url, :allow_redirections => :all).read


	# @result  = open(@download_url, :allow_redirections => :all) {|f| f.read }

	#  AudioInfo.open(@result) do |info|
	# 	  info.artist   # or info["artist"]
	# 	  info.title    # or info["title"]
	# 	  info.length   # playing time of the file
	# 	  info.bitrate  # average bitrate
	# 	  @info = info.to_h     # { "artist" => "artist", "title" => "title", etc... }
	#   end

end


def successs

end





end

app/views/home/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Connect with Soundcloud', user_omniauth_authorize_path(:soundcloud) if current_user unless @soundcloud_access_token %>

<% if @soundcloud_access_token != nil %>
	<h2><%= @sc.username %></h2>
	<p><%= @soundcloud_access_token %> | <%= @current_user.access_token %> </p>
	<p><%= @mixcloud_access_token %> </p>
	<ul>
		<% @tracks.each do |track| %>
			<li><%= link_to track.title, upload_path(:track => {title: track.title, download_url: track.download_url}), :method => :get %></li>
		<% end %>
	</ul>

<% end %>

<br/>
<%= link_to 'Connect with MixCloud', user_omniauth_authorize_path(:mixcloud) %>
<br/>
<% if current_user.id === 4 || 3 %>
<%= link_to 'Connect with Shopify', user_omniauth_authorize_path(:shopify, :params => {:shop=> 'ticktack.myshopify.com'}) %>
<% end %>

app/views/home/upload.html.erb
<h1>Upload to Mixcloud</h1>

<%= link_to "Download #{@title}", @download_url %>

<br/>
<p><%= @mixcloud_access_token %> </p>

<%= link_to "track", "recording9.m4a" %>
<br/>

<audio controls="controls">
  Your browser does not support the <code>audio</code> element.
  <source src="" type="audio/mp4">
</audio>
<br/>

<button id="upload" >Upload</button>

<script type="text/javascript">
		
	var mixcloud_access_token = "<%= @mixcloud_access_token %>";
	var download_url = "<%= @download_url %>";
	console.log(download_url);
	var file = "<%= @file %>";
	var name = "<%= @title %>";
	var	mixcloud_upload_url = "https://api.mixcloud.com/upload/?access_token="+mixcloud_access_token+"&mp3="+file+"&name="+name;

	$('button#upload').on('click', function(event) {
		console.log("fwjfwfjwifw");
		event.preventDefault()

		$.ajax({
		  type: "POST",
		  contentType: 'multipart/form-data',
		  url: mixcloud_upload_url
		})
		  .done(function( msg ) {
		    alert( "Data Saved: " + msg );
		  });

	});


</script>

app/views/home/welcome.html.erb
<h1>Welcome</h1>

<%= link_to "Sign up", new_user_registration_path %>